#!/bin/bash

source /data/people/shastin1/miniconda3/bin/activate trex
python -m baselines.run --alg=ppo2 --env="$1"NoFrameskip-v4 --custom_reward pytorch --custom_reward_path /data/people/shastin1/data/placeholder --seed 0 --num_timesteps=5e7 --save_path=/data/people/shastin1/trained_models/"$2"
