#!/bin/bash

source /data/people/shastin1/miniconda3/bin/activate trex

python LearnAtariReward.py --env_name "$1" --num_snippets 0 --num_trajs 3000
python VisualizeAtariLearnedReward.py --env_name "$1" --model_id s=0_t=3000
python utils/viz/quickviz.py --env_name "$1"_s=0_t=3000
