#!/bin/bash

source /data/people/shastin1/miniconda3/bin/activate trex

python LearnAtariReturn.py --env_name "$1" --num_snippets 0 --num_trajs 50000 --grid --data_only
python LearnAtariReturn.py --env_name "$1" --num_snippets 50000 --num_trajs 0 --grid --data_only
