#!/bin/bash

for var in "$@"
do
  bash grid_scripts/trax "$var"
  bash grid_scripts/trax "$var"
  bash grid_scripts/trax "$var"
  bash grid_scripts/bc "$var"
  bash grid_scripts/bc "$var"
  bash grid_scripts/bc "$var"
  bash grid_scripts/gail "$var"
  bash grid_scripts/gail "$var"
  bash grid_scripts/gail "$var"
  bash grid_scripts/trex "$var"
  bash grid_scripts/trex "$var"
  bash grid_scripts/trex "$var"
done
